In [1]:
import pandas as pd

In [69]:
add_data = pd.read_csv('../../datasets/addition_data.csv')

In [70]:
prev_data = pd.read_csv('../../datasets/merge.csv')

In [71]:
target_pivot = pd.read_csv('../../datasets/drug_target_pivot.csv')

In [72]:
add_data

                drug      atc
0      chlorhexidine  A01AB03
1         miconazole  A01AB09
2      metronidazole  A01AB17
3        doxycycline  A01AB22
4        minocycline  A01AB23
...              ...      ...
64970            NaN      NaN
64971            NaN      NaN
64972            NaN      NaN
64973            NaN      NaN
64974            NaN      NaN

[64975 rows x 2 columns]

In [73]:
add_data.dropna(axis=0,inplace=True)

In [74]:
add_data

              drug      atc
0    chlorhexidine  A01AB03
1       miconazole  A01AB09
2    metronidazole  A01AB17
3      doxycycline  A01AB22
4      minocycline  A01AB23
..             ...      ...
308  levetiracetam  N03AX14
309     zonisamide  N03AX15
310     pregabalin  N03AX16
311     lacosamide  N03AX18
312     perampanel  N03AX22

[313 rows x 2 columns]

In [75]:
prev_data

,Name,SMILES,DRUGBANK_ID,THROMBOCYTOPENIA
0,bivalirudin,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,DB00006,1
1,goserelin,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,DB00014,0
2,cetrorelix,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,DB00050,1
3,octreotide,[H][C@]1(NC(=O)[C@H](CCCCN)NC(=O)[C@@H](CC2=CN...,DB00104,0
4,pravastatin,[H][C@]12[C@H](C[C@H](O)C=C1C=C[C@H](C)[C@@H]2...,DB00175,0
...,...,...,...,...
781,domperidone,ClC1=CC2=C(C=C1)N(C1CCN(CCCN3C(=O)NC4=CC=CC=C3...,DB01184,0
782,mosapride,CCOC1=CC(N)=C(Cl)C=C1C(=O)NCC1CN(CC2=CC=C(F)C=...,DB11675,0
783,lactulose,OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O[C@@H]1O[...,DB00581,0
784,teneligliptin,[H][C@]1(CN[C@@]([H])(C1)C(=O)N1CCSC1)N1CCN(CC...,DB11950,0
785,ertugliflozin,CCOC1=CC=C(CC2=CC(=CC=C2Cl)[C@]23OC[C@](CO)(O2...,DB11827,0

In [76]:
duplicate_names = prev_data[prev_data.duplicated('Name', keep=False)]['Name'].unique()
duplicate_names

array(['tramadol', 'oseltamivir', 'phenytoin', 'flucloxacillin',
       'piperacillin', 'metformin', 'cetirizine', 'diltiazem',
       'aztreonam', 'mirtazapine', 'palonosetron', 'ceftazidime',
       'dicloxacillin', 'cefotaxime', 'haloperidol', 'cefdinir',
       'carbamazepine', 'diclofenac', 'linezolid', 'bisoprolol',
       'simvastatin', 'cefixime', 'furosemide', 'irinotecan', 'tirofiban',
       'naproxen', 'cefaclor', 'loperamide', 'tacrolimus', 'ondansetron',
       'felbamate', 'ibuprofen', 'amoxicillin', 'cefditoren',
       'cefuroxime', 'amiodarone', 'cefprozil', 'ceftriaxone',
       'quetiapine', 'metoclopramide', 'dexamethasone', 'sitagliptin',
       'cefepime', 'cefpodoxime', 'vildagliptin', 'alogliptin',
       'rivaroxaban', 'dapagliflozin', 'linagliptin', 'canagliflozin',
       'empagliflozin'], dtype=object)

In [77]:
df_unique = prev_data.drop_duplicates(subset=['Name'], keep='first')

In [78]:
df_unique

,Name,SMILES,DRUGBANK_ID,THROMBOCYTOPENIA
0,bivalirudin,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,DB00006,1
1,goserelin,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,DB00014,0
2,cetrorelix,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,DB00050,1
3,octreotide,[H][C@]1(NC(=O)[C@H](CCCCN)NC(=O)[C@@H](CC2=CN...,DB00104,0
4,pravastatin,[H][C@]12[C@H](C[C@H](O)C=C1C=C[C@H](C)[C@@H]2...,DB00175,0
...,...,...,...,...
781,domperidone,ClC1=CC2=C(C=C1)N(C1CCN(CCCN3C(=O)NC4=CC=CC=C3...,DB01184,0
782,mosapride,CCOC1=CC(N)=C(Cl)C=C1C(=O)NCC1CN(CC2=CC=C(F)C=...,DB11675,0
783,lactulose,OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O[C@@H]1O[...,DB00581,0
784,teneligliptin,[H][C@]1(CN[C@@]([H])(C1)C(=O)N1CCSC1)N1CCN(CC...,DB11950,0
785,ertugliflozin,CCOC1=CC=C(CC2=CC(=CC=C2Cl)[C@]23OC[C@](CO)(O2...,DB11827,0

In [19]:
target_pivot

,drug_id,"1,3-beta-glucan synthase component FKS1",14-3-3 protein beta/alpha,16S ribosomal RNA,"2-amino-3-ketobutyrate coenzyme A ligase, mitochondrial","2-oxoglutarate dehydrogenase, mitochondrial",23S ribosomal RNA,3 beta-hydroxysteroid dehydrogenase/Delta 5-->4-isomerase type 1,"3-beta-hydroxysteroid-Delta(8),Delta(7)-isomerase","3-carboxy-cis,cis-muconate cycloisomerase",...,"cAMP-specific 3',5'-cyclic phosphodiesterase 4A","cAMP-specific 3',5'-cyclic phosphodiesterase 4B","cAMP-specific 3',5'-cyclic phosphodiesterase 4C","cAMP-specific 3',5'-cyclic phosphodiesterase 4D","cGMP-inhibited 3',5'-cyclic phosphodiesterase A","cGMP-specific 3',5'-cyclic phosphodiesterase",fMet-Leu-Phe receptor,mRNA of ApoB-100,tRNA (cytosine(38)-C(5))-methyltransferase,vesicular monoamine transporter 2 (VMAT2)
0,DB00001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,DB00006,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,DB00007,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,DB00014,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,DB00016,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,DB14126,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
845,DB14500,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
846,DB14544,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
847,DB14569,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
848,DB14575,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
datasets_prev = pd.merge(target_pivot, prev_data, left_on='drug_id', right_on='DRUGBANK_ID')

In [29]:
cols = [col for col in prev_data.columns if col in datasets_prev.columns] + [col for col in datasets_prev.columns if col not in prev_data.columns]
datasets_prev = datasets_prev[cols]

In [30]:
datasets_prev

,Name,SMILES,DRUGBANK_ID,THROMBOCYTOPENIA,drug_id,"1,3-beta-glucan synthase component FKS1",14-3-3 protein beta/alpha,16S ribosomal RNA,"2-amino-3-ketobutyrate coenzyme A ligase, mitochondrial","2-oxoglutarate dehydrogenase, mitochondrial",...,"cAMP-specific 3',5'-cyclic phosphodiesterase 4A","cAMP-specific 3',5'-cyclic phosphodiesterase 4B","cAMP-specific 3',5'-cyclic phosphodiesterase 4C","cAMP-specific 3',5'-cyclic phosphodiesterase 4D","cGMP-inhibited 3',5'-cyclic phosphodiesterase A","cGMP-specific 3',5'-cyclic phosphodiesterase",fMet-Leu-Phe receptor,mRNA of ApoB-100,tRNA (cytosine(38)-C(5))-methyltransferase,vesicular monoamine transporter 2 (VMAT2)
0,bivalirudin,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,DB00006,1,DB00006,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,goserelin,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,DB00014,0,DB00014,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,cetrorelix,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,DB00050,1,DB00050,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,daptomycin,CCCCCCCCCC(=O)N[C@@H](CC1=CNC2=C1C=CC=C2)C(=O)...,DB00080,1,DB00080,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,octreotide,[H][C@]1(NC(=O)[C@H](CCCCN)NC(=O)[C@@H](CC2=CN...,DB00104,0,DB00104,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,tropisetron,[H][C@]12CC[C@]([H])(C[C@@]([H])(C1)OC(=O)C1=C...,DB11699,0,DB11699,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
708,clobetasone,[H][C@]1(C)C[C@@]2([H])[C@]3([H])CCC4=CC(=O)C=...,DB13158,0,DB13158,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
709,fluticasone,[H][C@@]12C[C@@H](C)[C@](O)(C(=O)SCF)[C@@]1(C)...,DB13867,0,DB13867,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
710,candesartan,CCOC1=NC2=CC=CC(C(O)=O)=C2N1CC1=CC=C(C=C1)C1=C...,DB13919,1,DB13919,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
711,eslicarbazepine,NC(=O)N1C2=C(C[C@H](O)C3=C1C=CC=C3)C=CC=C2,DB14575,1,DB14575,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
duplicate_names = datasets_prev[datasets_prev.duplicated('Name', keep=False)]['Name'].unique()
duplicate_names

array(['tramadol', 'oseltamivir', 'phenytoin', 'flucloxacillin',
       'piperacillin', 'metformin', 'cetirizine', 'diltiazem',
       'aztreonam', 'mirtazapine', 'palonosetron', 'ceftazidime',
       'dicloxacillin', 'cefotaxime', 'haloperidol', 'cefdinir',
       'carbamazepine', 'diclofenac', 'linezolid', 'bisoprolol',
       'simvastatin', 'cefixime', 'furosemide', 'irinotecan', 'tirofiban',
       'naproxen', 'cefaclor', 'loperamide', 'tacrolimus', 'ondansetron',
       'felbamate', 'ibuprofen', 'amoxicillin', 'cefditoren',
       'cefuroxime', 'amiodarone', 'cefprozil', 'ceftriaxone',
       'quetiapine', 'metoclopramide', 'dexamethasone', 'sitagliptin',
       'cefepime', 'cefpodoxime', 'vildagliptin', 'alogliptin',
       'rivaroxaban', 'dapagliflozin', 'linagliptin', 'canagliflozin',
       'empagliflozin'], dtype=object)

In [49]:
df_unique = datasets_prev.drop_duplicates(subset=['Name'], keep='first')

In [53]:
df_unique.to_csv('../../datasets/smile_target_dataset.csv', index = False)

In [54]:
df_unique

,Name,SMILES,DRUGBANK_ID,THROMBOCYTOPENIA,drug_id,"1,3-beta-glucan synthase component FKS1",14-3-3 protein beta/alpha,16S ribosomal RNA,"2-amino-3-ketobutyrate coenzyme A ligase, mitochondrial","2-oxoglutarate dehydrogenase, mitochondrial",...,"cAMP-specific 3',5'-cyclic phosphodiesterase 4A","cAMP-specific 3',5'-cyclic phosphodiesterase 4B","cAMP-specific 3',5'-cyclic phosphodiesterase 4C","cAMP-specific 3',5'-cyclic phosphodiesterase 4D","cGMP-inhibited 3',5'-cyclic phosphodiesterase A","cGMP-specific 3',5'-cyclic phosphodiesterase",fMet-Leu-Phe receptor,mRNA of ApoB-100,tRNA (cytosine(38)-C(5))-methyltransferase,vesicular monoamine transporter 2 (VMAT2)
0,bivalirudin,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,DB00006,1,DB00006,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,goserelin,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,DB00014,0,DB00014,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,cetrorelix,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,DB00050,1,DB00050,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,daptomycin,CCCCCCCCCC(=O)N[C@@H](CC1=CNC2=C1C=CC=C2)C(=O)...,DB00080,1,DB00080,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,octreotide,[H][C@]1(NC(=O)[C@H](CCCCN)NC(=O)[C@@H](CC2=CN...,DB00104,0,DB00104,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,tropisetron,[H][C@]12CC[C@]([H])(C[C@@]([H])(C1)OC(=O)C1=C...,DB11699,0,DB11699,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
708,clobetasone,[H][C@]1(C)C[C@@]2([H])[C@]3([H])CCC4=CC(=O)C=...,DB13158,0,DB13158,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
709,fluticasone,[H][C@@]12C[C@@H](C)[C@](O)(C(=O)SCF)[C@@]1(C)...,DB13867,0,DB13867,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
710,candesartan,CCOC1=NC2=CC=CC(C(O)=O)=C2N1CC1=CC=C(C=C1)C1=C...,DB13919,1,DB13919,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
711,eslicarbazepine,NC(=O)N1C2=C(C[C@H](O)C3=C1C=CC=C3)C=CC=C2,DB14575,1,DB14575,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
filtered_df = df_unique[df_unique['Name'].isin(add_data['drug'])]

In [80]:
filtered_df

,Name,SMILES,DRUGBANK_ID,THROMBOCYTOPENIA
4,pravastatin,[H][C@]12[C@H](C[C@H](O)C=C1C=C[C@H](C)[C@@H]2...,DB00175,0
13,bortezomib,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,DB00188,1
17,fluconazole,OC(CN1C=NC=N1)(CN1C=NC=N1)C1=C(F)C=C(F)C=C1,DB00196,0
19,oseltamivir,CCOC(=O)C1=C[C@@H](OC(CC)CC)[C@H](NC(C)=O)[C@@...,DB00198,0
23,dofetilide,CN(CCOC1=CC=C(NS(C)(=O)=O)C=C1)CCC1=CC=C(NS(C)...,DB00204,0
...,...,...,...,...
771,quinidine,[H][C@@]12CCN(C[C@@H]1C=C)[C@]([H])(C2)[C@@H](...,DB00908,1
776,teicoplanin,CCCCCCCCCC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](...,DB06149,1
778,ticarcillin,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)[C@...,DB01607,1
779,valproic acid,CCCC(CCC)C(O)=O,DB00313,1
780,vancomycin,CN[C@H](CC(C)C)C(=O)N[C@@H]1[C@H](O)C2=CC=C(OC...,DB00512,1

In [81]:
filtered_df.to_csv('../../datasets/datasets_smiles.csv', index = False)

In [82]:
import requests

In [83]:
def get_approval_date(drug_name):
    url = f'https://api.fda.gov/drug/drugsfda.json?search=products.brand_name:"{drug_name}"&limit=1'
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        try:
            submissions = data['results'][0]['submissions']
            # 승인연도들 추출
            approval_dates = [submission['submission_status_date'] for submission in submissions]
            # 가장 오래된 승인연도 찾기
            approval_date = min(approval_dates)  # YYYYMMDD 형식으로 전체 날짜 추출
            return approval_date
        except (KeyError, IndexError):
            return None
    else:
        return None

In [85]:
from tqdm import tqdm

In [88]:
approval_dates = []

for drug in tqdm(filtered_df['Name']):
    date = get_approval_date(drug)
    approval_dates.append(date)

filtered_df['ApprovalDate'] = approval_dates

# None 값을 가진 행 제거
# df = df.dropna(subset=['ApprovalDate'])

# 네 번째 열에 ApprovalDate를 추가하고 나머지 열들을 그대로 유지
cols = list(filtered_df.columns)
cols.insert(3, cols.pop(-1))
filtered_df = filtered_df[cols]

# 승인 날짜 기준으로 정렬 (오래된 날짜일수록 위로)
filtered_df['ApprovalDate'] = pd.to_datetime(filtered_df['ApprovalDate'], format='%Y%m%d')
filtered_df = filtered_df.sort_values(by='ApprovalDate')

100%|██████████| 298/298 [02:25<00:00,  2.05it/s]
C:\Users\MSY\AppData\Local\Temp\ipykernel_142932\991735373.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['ApprovalDate'] = approval_dates

In [89]:
filtered_df

,Name,SMILES,DRUGBANK_ID,ApprovalDate,THROMBOCYTOPENIA
325,cefaclor,[H][C@]12SCC(Cl)=C(N1C(=O)[C@H]2NC(=O)[C@H](N)...,DB00833,1979-07-28,1
400,hydrochlorothiazide,NS(=O)(=O)C1=C(Cl)C=C2NCNS(=O)(=O)C2=C1,DB00999,1981-08-20,1
163,dicloxacillin,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)C1=...,DB00485,1982-06-03,1
142,trimethoprim,COC1=CC(CC2=CN=C(N)N=C2N)=CC(OC)=C1OC,DB00440,1983-05-09,0
139,ceftazidime,[O-]C(=O)C1=C(CS[C@]2([H])[C@H](NC(=O)C(=N/OC(...,DB00438,1985-11-20,1
...,...,...,...,...,...
766,pivampicillin,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)[C@...,DB01604,NaT,1
767,pivmecillinam,[H]C(=N[C@@H]1C(=O)N2[C@@H](C(=O)OCOC(=O)C(C)(...,DB01605,NaT,1
771,quinidine,[H][C@@]12CCN(C[C@@H]1C=C)[C@]([H])(C2)[C@@H](...,DB00908,NaT,1
776,teicoplanin,CCCCCCCCCC(=O)N[C@@H]1[C@@H](O)[C@H](O)[C@@H](...,DB06149,NaT,1
778,ticarcillin,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)[C@...,DB01607,NaT,1

In [96]:
filtered_df.sort_values(by='ApprovalDate', na_position = 'first', ascending=False )

,Name,SMILES,DRUGBANK_ID,ApprovalDate,THROMBOCYTOPENIA
13,bortezomib,CC(C)C[C@H](NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)C1=...,DB00188,NaT,1
19,oseltamivir,CCOC(=O)C1=C[C@@H](OC(CC)CC)[C@H](NC(C)=O)[C@@...,DB00198,NaT,0
29,torasemide,CC(C)NC(=O)NS(=O)(=O)C1=C(NC2=CC=CC(C)=C2)C=CN=C1,DB00214,NaT,0
33,nelfinavir,[H][C@@]12CCCC[C@]1([H])CN(C[C@@H](O)[C@H](CSC...,DB00220,NaT,1
35,indinavir,CC(C)(C)NC(=O)[C@@H]1CN(CC2=CN=CC=C2)CCN1C[C@@...,DB00224,NaT,0
...,...,...,...,...,...
139,ceftazidime,[O-]C(=O)C1=C(CS[C@]2([H])[C@H](NC(=O)C(=N/OC(...,DB00438,1985-11-20,1
142,trimethoprim,COC1=CC(CC2=CN=C(N)N=C2N)=CC(OC)=C1OC,DB00440,1983-05-09,0
163,dicloxacillin,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)C1=...,DB00485,1982-06-03,1
400,hydrochlorothiazide,NS(=O)(=O)C1=C(Cl)C=C2NCNS(=O)(=O)C2=C1,DB00999,1981-08-20,1
325,cefaclor,[H][C@]12SCC(Cl)=C(N1C(=O)[C@H]2NC(=O)[C@H](N)...,DB00833,1979-07-28,1

In [97]:
filtered_df.to_csv('../../datasets/datasets_smiles_approval.csv', index = False)

In [91]:
target = pd.read_csv('../../datasets/smile_target_dataset.csv')

In [92]:
approval_dates = []

for drug in tqdm(target['Name']):
    date = get_approval_date(drug)
    approval_dates.append(date)

target['ApprovalDate'] = approval_dates

# None 값을 가진 행 제거
# df = df.dropna(subset=['ApprovalDate'])

# 네 번째 열에 ApprovalDate를 추가하고 나머지 열들을 그대로 유지
cols = list(target.columns)
cols.insert(3, cols.pop(-1))
target = target[cols]

# 승인 날짜 기준으로 정렬 (오래된 날짜일수록 위로)
target['ApprovalDate'] = pd.to_datetime(target['ApprovalDate'], format='%Y%m%d')
target = target.sort_values(by='ApprovalDate')

100%|██████████| 661/661 [05:24<00:00,  2.04it/s]

In [98]:
target.sort_values(by='ApprovalDate', na_position = 'first', ascending=False )

,Name,SMILES,DRUGBANK_ID,ApprovalDate,THROMBOCYTOPENIA,drug_id,"1,3-beta-glucan synthase component FKS1",14-3-3 protein beta/alpha,16S ribosomal RNA,"2-amino-3-ketobutyrate coenzyme A ligase, mitochondrial",...,"cAMP-specific 3',5'-cyclic phosphodiesterase 4A","cAMP-specific 3',5'-cyclic phosphodiesterase 4B","cAMP-specific 3',5'-cyclic phosphodiesterase 4C","cAMP-specific 3',5'-cyclic phosphodiesterase 4D","cGMP-inhibited 3',5'-cyclic phosphodiesterase A","cGMP-specific 3',5'-cyclic phosphodiesterase",fMet-Leu-Phe receptor,mRNA of ApoB-100,tRNA (cytosine(38)-C(5))-methyltransferase,vesicular monoamine transporter 2 (VMAT2)
1,goserelin,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,DB00014,NaT,0,DB00014,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,cetrorelix,CC(C)C[C@H](NC(=O)[C@@H](CCCNC(N)=O)NC(=O)[C@H...,DB00050,NaT,1,DB00050,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,daptomycin,CCCCCCCCCC(=O)N[C@@H](CC1=CNC2=C1C=CC=C2)C(=O)...,DB00080,NaT,1,DB00080,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,baclofen,NCC(CC(O)=O)C1=CC=C(Cl)C=C1,DB00181,NaT,0,DB00181,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,esmolol,COC(=O)CCC1=CC=C(OCC(O)CNC(C)C)C=C1,DB00187,NaT,0,DB00187,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,hydrochlorothiazide,NS(=O)(=O)C1=C(Cl)C=C2NCNS(=O)(=O)C2=C1,DB00999,1981-08-20,1,DB00999,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
219,triamcinolone,[H][C@@]12C[C@@H](O)[C@](O)(C(=O)CO)[C@@]1(C)C...,DB00620,1981-04-09,0,DB00620,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
304,cefaclor,[H][C@]12SCC(Cl)=C(N1C(=O)[C@H]2NC(=O)[C@H](N)...,DB00833,1979-07-28,1,DB00833,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
386,bethanechol,CC(C[N+](C)(C)C)OC(N)=O,DB01019,1976-07-01,0,DB01019,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
295,dicyclomine,CCN(CC)CCOC(=O)C1(CCCCC1)C1CCCCC1,DB00804,1975-06-23,1,DB00804,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [99]:
target.to_csv('../../datasets/datasets_target_smiles_approval.csv', index = False)